### ISSUE TITLE
pymatgen 2019.7.30 on conda-forge vs. matsci 

### ISSUE THREAD

**Issue by jan-janssen** [materialsvirtuallab/materials.sh#4]
I recently started to push pymatgen to the conda-forge channel and noticed that you stopped updating the matsci channel - did not upgrade pymatgen after 2019.6.5. So I was wondering if it makes sense to convert the recipes in this repository to conda-forge. Some of the packages might need some more fixes to be compatible to the conda-forge requirements but I guess in general it would help the materials science community to have all packages integrated in the conda-forge channel.

**Comment by shyuep** [comment]
Thanks for the comment. I agree it would be ideal if everything can be integrated into the conda-forge. I started with conda-forge, but I later found that it was complicated maintaining so many different recipes for the dependencies, especially since I am not the original authors for any of them except for monty and pymatgen. That was when I decided to set up a matsci channel and build these myself so that I have control over the versions.

Actually the matsci channel is indeed updated regularly. I am not sure why the July 2019 releases are not in there. Probably something broke in the automated release procedure (@mkhorton ?). I will release a new version with new matsci versions.

If you can somehow make everything work with conda-forge, I will be happy to deprecate this channel entirely.

**Comment by mkhorton** [comment]
> Probably something broke in the automated release procedure 

Yes, possibly. My only involvement with the conda side has been to push to the materials.sh repo when releasing a new version of pymatgen, e.g. see https://github.com/materialsvirtuallab/materials.sh/commit/d925ca015f87fe379bfb735320fd9b71936b5d6c Have I missed a step here?

**Comment by jan-janssen** [comment]
I take a look at migrating the other packages at the weekend, by the way should I add both of you to the pymatgen conda-forge recipe https://github.com/conda-forge/pymatgen-feedstock ?

**Comment by jan-janssen** [comment]
The packages are migrated except: 

- matmethods - updated 2016-12-09 - removed from recipes 
- enumlib - updated 2017-07-16 - removed from recipes 
- boltztrap - updated 2017-07-16 - superseded by boltztrap2 (not yet available on either conda-forge or matsci) 
- bader - updated 2018-03-10 

So I guess the users should now be able to migrate to the conda-forge channel and if somebody is interested to migrate the remaining four packages, just pin me for support.

**Comment by shyuep** [comment]
Thanks @jan-janssen . Thanks for doing this. You can ignore those four recipes for now. And yes, please add me and @mkhorton to the pymatgen and pymatgen-* recipes.

**Comment by jan-janssen** [comment]
Sure, I added both of you to the list of maintainers for pymatgen, pymatgen-db and pymatgen-diffusion. You should have received an email with the invitation to the conda-forge user group.
